### ISSUE TITLE
Cannot read property 'createLTR' of undefined

### ISSUE THREAD

**Issue by ngankt2** [airbnb/react-with-styles#137] opened 2018-04-17 03:42 UTC
Ussing: https://github.com/airbnb/react-dates

**server render**

Cannot read property 'createLTR' of undefined
TypeError: Cannot read property 'createLTR' of undefined
    at Object.createLTR (/usr/src/app/node_modules/react-with-styles/lib/ThemedStyleSheet.js:23:47)
    at createStyles (/usr/src/app/node_modules/react-with-styles/lib/withStyles.js:105:59)
    at WithStyles.maybeCreateStyles (/usr/src/app/node_modules/react-with-styles/lib/withStyles.js:200:22)
    at WithStyles.componentWillMount (/usr/src/app/node_modules/react-with-styles/lib/withStyles.js:134:20)
    at u.performInitialMount (/usr/src/app/server.bundle.js:15:553194)
    at u.mountComponent (/usr/src/app/server.bundle.js:15:552366)
    at Object.mountComponent (/usr/src/app/server.bundle.js:1:96042)
    at X.mountChildren (/usr/src/app/server.bundle.js:15:559600)
    at X._createContentMarkup (/usr/src/app/server.bundle.js:15:591579)
    at X.mountComponent (/usr/src/app/server.bundle.js:15:590247)
    at Object.mountComponent (/usr/src/app/server.bundle.js:1:96042)
    at X.mountChildren (/usr/src/app/server.bundle.js:15:559600)
    at X._createContentMarkup (/usr/src/app/server.bundle.js:15:591579)
    at X.mountComponent (/usr/src/app/server.bundle.js:15:590247)
    at Object.mountComponent (/usr/src/app/server.bundle.js:1:96042)
    at X.mountChildren (/usr/src/app/server.bundle.js:15:559600)
    at X._createContentMarkup (/usr/src/app/server.bundle.js:15:591579)
    at X.mountComponent (/usr/src/app/server.bundle.js:15:590247)
    at Object.mountComponent (/usr/src/app/server.bundle.js:1:96042)
    at X.mountChildren (/usr/src/app/server.bundle.js:15:559600)
    at X._createContentMarkup (/usr/src/app/server.bundle.js:15:591579)
    at X.mountComponent (/usr/src/app/server.bundle.js:15:590247)

**Comment by alexmcmillan** [comment] 2018-05-23 23:05
I'm seeing the same thing.

`createLTR` is called on a variable called `styleInterface` (declared [here](https://github.com/airbnb/react-with-styles/blob/master/src/ThemedStyleSheet.js#L1)).  The only place this variable is given a value is in [registerInterface()](https://github.com/airbnb/react-with-styles/blob/master/src/ThemedStyleSheet.js#L9) which is exported [here](https://github.com/airbnb/react-with-styles/blob/master/src/ThemedStyleSheet.js#L81).

`withStyles.js` [imports](https://github.com/airbnb/react-with-styles/blob/master/src/withStyles.jsx#L9) the entire module as `ThemedStyleSheet` but _never calls `ThemedStyleSheet.registerInterface`.

As these are the only 2 source files in this repository, I don't see how this could possibly work at all, for anybody.

Is there anybody who can help us understand this?  It's preventing our use of the excellent `react-dates` package.

**Comment by alexmcmillan** [comment] 2018-05-23 23:16
I had the same problem; turns out it was a RTFM issue.

From [the react-dates readme](https://github.com/airbnb/react-dates#initialize):

> **Initialize**
>
> ```import 'react-dates/initialize';```
>
> As of v13.0.0 of react-dates, this project relies on react-with-styles. If you want to continue using CSS stylesheets and classes, there is a little bit of extra set-up required to get things going. As such, you need to import react-dates/initialize to set up class names on our components. This import should go at the top of your application as you won't be able to import any react-dates components without it.

**Comment by RayBowman2017b** [comment] 2018-10-25 17:21
Same problem here.

This did not work:
import 'react-dates/initialize';

Downgrading to 12.7.0, as @kakadiadarpan mentioned, solved this.

The code is there:
https://github.com/RayBowman2017b/react-course-2-r-17-10

**Comment by SaiKrishnaMohan7** [comment] 2018-10-25 23:54
@RayBowman2017b encountered the same issue. Working on the same app! I have downgraded as well! Thank you for posting this here.

**Comment by josholiver** [comment] 2018-11-28 16:59
@alexmcmillan Thanks. It worked.

**Comment by Adam-Burke** [comment] 2018-12-01 01:21
So you have to downgrade 6 major releases to fix this bug?

**Comment by ljharb** [comment] 2018-12-01 01:29
That shouldn’t be necessary. Using the latest version with importing the initialize entry point should work.

**Comment by cptiwari20** [comment] 2018-12-02 15:56
Yes, i had the same issue. But after importing the initialize entry point it has been solve.

`import 'react-dates/initialize'; // necessary for latest version
import { SingleDatePicker } from 'react-dates';
import 'react-dates/lib/css/_datepicker.css';`

**Comment by darieldejesus** [comment] 2018-12-06 04:40
As @alexmcmillan said, this is required by default because of the dependency with `react-with-styled`. And as the solution he linked, you just need to import the initializer at the beginning of the app (could be located in the `index.js` file or you can include it at the beginning of the component file).

On the other hand, I had the error when trying to run the tests using Jest. I just had to import the initializer at the beginning of the test file and that fixed the issue. 

Note ⚠️ : if you decide to include the initializer (`"react-dates/initialize"`) in the component file, you don't need to include it here.

File: `SingleDatePicket.test.tsx`
```js
import * as React from "react";
import "jest-styled-components";
import renderer from 'react-test-renderer';
import "react-dates/initialize"; <===========================================

import MySingleDatePicker from "../MySingleDatePicker";
...
describe("MySingleDatePicker", () => {
  it("Should render correctly", () => {
    const component = renderer.create(
      <MySingleDatePicker
        value={null}
      />
    ).toJSON();
    expect(tree).toMatchSnapshot();
  });
});
```

**Comment by omarzion** [comment] 2018-12-12 17:49
I am bundling a component that wraps react-dates into a component library that transpiles to cjs with rollup.  Using `import 'react-dates/initialize'` in the wrapping component no longer works

**Comment by ljharb** [comment] 2018-12-12 17:57
It’s possible rollup is incorrectly removing code; it wouldn’t be the first time. Can you reproduce it with browserify or webpack?

**Comment by IkwhanChang** [comment] 2019-01-25 22:49
Using import 'react-dates/initialize' is working for me.

**Comment by gazgump** [comment] 2019-02-22 17:17
I was struggling for a minute there - you need to add the css link too - 

import 'react-dates/lib/css/_datepicker.css';

Doh!

**Comment by ljharb** [comment] 2019-02-22 18:11
Closing; this seems answered.

**Closed by ljharb** 2019-02-22 18:11 UTC

**Comment by tstirrat15** [comment] 2019-06-13 21:45
I'm running into the same problem. I've got the initializer at the top of the component file, and I'm getting this error:
```javascript
react_1          | TypeError: Cannot read property 'createLTR' of undefined
react_1          |     at Object.createLTR (/usr/src/app/node_modules/react-with-styles/lib/ThemedStyleSheet.js:23:47)
react_1          |     at getStyleDef (/usr/src/app/node_modules/react-with-styles/lib/withStyles.js:129:61)
react_1          |     at getState (/usr/src/app/node_modules/react-with-styles/lib/withStyles.js:147:17)
react_1          |     at new WithStyles (/usr/src/app/node_modules/react-with-styles/lib/withStyles.js:168:25)
react_1          |     at processChild (/usr/src/app/build/webpack:/node_modules/react-dom/cjs/react-dom-server.node.development.js:2098:1)
react_1          |     at resolve (/usr/src/app/build/webpack:/node_modules/react-dom/cjs/react-dom-server.node.development.js:2064:1)
react_1          |     at ReactDOMServerRenderer.render (/usr/src/app/build/webpack:/node_modules/react-dom/cjs/react-dom-server.node.development.js:2383:1)
react_1          |     at ReactDOMServerRenderer.read (/usr/src/app/build/webpack:/node_modules/react-dom/cjs/react-dom-server.node.development.js:2357:1)
react_1          |     at renderToString (/usr/src/app/build/webpack:/node_modules/react-dom/cjs/react-dom-server.node.development.js:2729:1)
react_1          |     at /usr/src/app/build/webpack:/render.js:103:1
react_1          |     at process._tickCallback (internal/process/next_tick.js:68:7)
```

This is in a server-side rendered application. Is there anything that would prevent either `react-dates` or `react-with-styles` from working in a server context?

**Comment by matthlavacka** [comment] 2020-01-04 13:10
@tstirrat15 Have you managed to figure this out? Same issue here

**Comment by tstirrat15** [comment] 2020-01-07 14:07
@matthlavacka We're no longer experiencing the issue, but I can't figure out exactly what fixed it - we ran in to this issue, tabled the upgrade for a few months, and when I came back to it, it Just Worked^tm somehow.

We're on react 16.10 now, and we're using `webpack-node-externals` for externalization, though neither `react` or `react-dom` is externalized.

One thing to check is that you're only pulling one copy of react into your project - `duplicate-package-checker-webpack-plugin` can help with that.

**Comment by matthlavacka** [comment] 2020-01-13 22:00
thanks for your reply @tstirrat15, I decided to use different package to not waste time.

**Comment by sunapi386** [comment] 2020-04-20 05:12
Ran into this, but too many dependencies and came across some issues, so decided to use another package instead.
I got far enough to get this screenshot with the following code.
(I'm using typescript)
```
yarn add react-dates @types/react-dates moment @types/moment
[...]
import 'react-dates/initialize';
import { DateRangePicker } from "react-dates"
import 'react-dates/lib/css/_datepicker.css';
[...]
<DateRangePicker
          startDate={null} // momentPropTypes.momentObj or null,
          startDateId="your_unique_start_date_id" // PropTypes.string.isRequired,
          endDate={null} // momentPropTypes.momentObj or null,
          endDateId="your_unique_end_date_id" // PropTypes.string.isRequired,
          onDatesChange={({ startDate, endDate }) => console.log(startDate, endDate)} // PropTypes.func.isRequired,
          focusedInput={null} // PropTypes.oneOf([START_DATE, END_DATE]) or null,
          onFocusChange={focusedInput => console.log(focusedInput)} // PropTypes.func.isRequired,
        />
```
![image](https://user-images.githubusercontent.com/1029022/79715595-00933800-8289-11ea-90cb-f5b18d597e83.png)
But clicking on the date input doesn't bring up selection box as expected. 

Anyways, went with something else, easier. 

![image](https://user-images.githubusercontent.com/1029022/79716186-ccb91200-828a-11ea-9706-c43fa614e462.png)


http://onefinestay.github.io/react-daterange-picker/
```
yarn add @types/react-daterange-picker 
[...]
import DateRangePicker from "react-daterange-picker"
import 'react-daterange-picker/dist/css/react-calendar.css' // For some basic styling. (OPTIONAL)
[...]
<DateRangePicker
          numberOfCalendars={2}
          selectionType="range"
          minimumDate={new Date()} />
```

**Comment by picozzimichele** [comment] 2020-06-04 07:19
this worked for me 

`import 'react-dates/initialize'`

**Comment by yashdeora** [comment] 2020-08-11 09:18
I have the same problem that but the code is exactly the same. am using react [programming](https://www.programmingoneonone.com/).

**Comment by akshayjai1** [comment] 2020-08-12 11:24
> Yes, i had the same issue. But after importing the initialize entry point it has been solve.
> 
> `import 'react-dates/initialize'; // necessary for latest version import { SingleDatePicker } from 'react-dates'; import 'react-dates/lib/css/_datepicker.css';`

Worked!

**Comment by omer-jan** [comment] 2020-10-01 18:17
> Same problem here.
> 
> This did not work:
> import 'react-dates/initialize';
> 
> Downgrading to 12.7.0, as @kakadiadarpan mentioned, solved this.
> 
> The code is there:
> https://github.com/RayBowman2017b/react-course-2-r-17-10

thanks it is work for me

**Comment by jagtarsinghwork** [comment] 2021-05-17 06:16
Nothing need just import thiese 2 lines where you date import above this import these
or Another way 
in main.js or index js  paste these line 

 import "react-dates/initialize";
import "react-dates/lib/css/_datepicker.css";
import { SingleDatePicker } from "react-dates";

**Comment by MohammadSamirAskan** [comment] 2021-06-07 12:56
it's working thank you.

**Comment by gecko25** [comment] 2021-11-14 18:26
I had to remove my node modules and reinstall them.

**Comment by carlosaflach** [comment] 2023-03-06 19:49
I had the same problem here, apparently remove node modules and reinstall them worked.
