### ISSUE TITLE
React SSR - Cannot read property 'createLTR' of undefined

### ISSUE THREAD

**Issue by HakanSungur** [airbnb/react-with-styles#256] opened 2024-05-30 23:12 UTC
ypeError: Cannot read property 'createLTR' of undefined
    at makeCreateFn (C:\Users\Administrator\Desktop\Vacbid\holioff\node_modules\react-with-styles\lib\withStyles.js:154:33)
    at WithStyles.getProps (C:\Users\Administrator\Desktop\Vacbid\holioff\node_modules\react-with-styles\lib\withStyles.js:236:44)
    at WithStyles.render (C:\Users\Administrator\Desktop\Vacbid\holioff\node_modules\react-with-styles\lib\withStyles.js:292:35)
    at finishClassComponent (C:\Users\Administrator\Desktop\Vacbid\holioff\node_modules\react-dom\cjs\react-dom-server.node.development.js:5729:31)
    at renderClassComponent (C:\Users\Administrator\Desktop\Vacbid\holioff\node_modules\react-dom\cjs\react-dom-server.node.development.js:5762:3)
    at renderElement (C:\Users\Administrator\Desktop\Vacbid\holioff\node_modules\react-dom\cjs\react-dom-server.node.development.js:6020:7)
    at renderNodeDestructiveImpl (C:\Users\Administrator\Desktop\Vacbid\holioff\node_modules\react-dom\cjs\react-dom-server.node.development.js:6181:11)
    at renderNodeDestructive (C:\Users\Administrator\Desktop\Vacbid\holioff\node_modules\react-dom\cjs\react-dom-server.node.development.js:6153:14)
    at renderForwardRef (C:\Users\Administrator\Desktop\Vacbid\holioff\node_modules\react-dom\cjs\react-dom-server.node.development.js:5936:5)
    at renderElement (C:\Users\Administrator\Desktop\Vacbid\holioff\node_modules\react-dom\cjs\react-dom-server.node.development.js:6082:11)
    at renderNodeDestructiveImpl (C:\Users\Administrator\Desktop\Vacbid\holioff\node_modules\react-dom\cjs\react-dom-server.node.development.js:6181:11)
    at renderNodeDestructive (C:\Users\Administrator\Desktop\Vacbid\holioff\node_modules\react-dom\cjs\react-dom-server.node.development.js:6153:14)
    at renderNode (C:\Users\Administrator\Desktop\Vacbid\holioff\node_modules\react-dom\cjs\react-dom-server.node.development.js:6336:12)
    at renderHostElement (C:\Users\Administrator\Desktop\Vacbid\holioff\node_modules\react-dom\cjs\react-dom-server.node.development.js:5708:3)
    at renderElement (C:\Users\Administrator\Desktop\Vacbid\holioff\node_modules\react-dom\cjs\react-dom-server.node.development.js:6029:5)
    at renderNodeDestructiveImpl (C:\Users\Administrator\Desktop\Vacbid\holioff\node_modules\react-dom\cjs\react-dom-server.node.development.js:6181:11)
    at renderNodeDestructive (C:\Users\Administrator\Desktop\Vacbid\holioff\node_modules\react-dom\cjs\react-dom-server.node.development.js:6153:14)
    at renderNode (C:\Users\Administrator\Desktop\Vacbid\holioff\node_modules\react-dom\cjs\react-dom-server.node.development.js:6336:12)
    at renderChildrenArray (C:\Users\Administrator\Desktop\Vacbid\holioff\node_modules\react-dom\cjs\react-dom-server.node.development.js:6288:7)
    at renderNodeDestructiveImpl (C:\Users\Administrator\Desktop\Vacbid\holioff\node_modules\react-dom\cjs\react-dom-server.node.development.js:6218:7)
    at renderNodeDestructive (C:\Users\Administrator\Desktop\Vacbid\holioff\node_modules\react-dom\cjs\react-dom-server.node.development.js:6153:14)
    at renderNode (C:\Users\Administrator\Desktop\Vacbid\holioff\node_modules\react-dom\cjs\react-dom-server.node.development.js:6336:12)
    at renderHostElement (C:\Users\Administrator\Desktop\Vacbid\holioff\node_modules\react-dom\cjs\react-dom-server.node.development.js:5708:3)
    at renderElement (C:\Users\Administrator\Desktop\Vacbid\holioff\node_modules\react-dom\cjs\react-dom-server.node.development.js:6029:5)
    at renderNodeDestructiveImpl (C:\Users\Administrator\Desktop\Vacbid\holioff\node_modules\react-dom\cjs\react-dom-server.node.development.js:6181:11)
    at renderNodeDestructive (C:\Users\Administrator\Desktop\Vacbid\holioff\node_modules\react-dom\cjs\react-dom-server.node.development.js:6153:14)
    at renderIndeterminateComponent (C:\Users\Administrator\Desktop\Vacbid\holioff\node_modules\react-dom\cjs\react-dom-server.node.development.js:5852:7)
    at renderElement (C:\Users\Administrator\Desktop\Vacbid\holioff\node_modules\react-dom\cjs\react-dom-server.node.development.js:6023:7)
    at renderNodeDestructiveImpl (C:\Users\Administrator\Desktop\Vacbid\holioff\node_modules\react-dom\cjs\react-dom-server.node.development.js:6181:11)
    at renderNodeDestructive (C:\Users\Administrator\Desktop\Vacbid\holioff\node_modules\react-dom\cjs\react-dom-server.node.development.js:6153:14)
    at renderNode (C:\Users\Administrator\Desktop\Vacbid\holioff\node_modules\react-dom\cjs\react-dom-server.node.development.js:6336:12)
    at renderChildrenArray (C:\Users\Administrator\Desktop\Vacbid\holioff\node_modules\react-dom\cjs\react-dom-server.node.development.js:6288:7)
    at renderNodeDestructiveImpl (C:\Users\Administrator\Desktop\Vacbid\holioff\node_modules\react-dom\cjs\react-dom-server.node.development.js:6218:7)
    at renderNodeDestructive (C:\Users\Administrator\Desktop\Vacbid\holioff\node_modules\react-dom\cjs\react-dom-server.node.development.js:6153:14)
    at renderNode (C:\Users\Administrator\Desktop\Vacbid\holioff\node_modules\react-dom\cjs\react-dom-server.node.development.js:6336:12)
    at renderHostElement (C:\Users\Administrator\Desktop\Vacbid\holioff\node_modules\react-dom\cjs\react-dom-server.node.development.js:5708:3)
    at renderElement (C:\Users\Administrator\Desktop\Vacbid\holioff\node_modules\react-dom\cjs\react-dom-server.node.development.js:6029:5)
    at renderNodeDestructiveImpl (C:\Users\Administrator\Desktop\Vacbid\holioff\node_modules\react-dom\cjs\react-dom-server.node.development.js:6181:11)
    at renderNodeDestructive (C:\Users\Administrator\Desktop\Vacbid\holioff\node_modules\react-dom\cjs\react-dom-server.node.development.js:6153:14)
    at renderIndeterminateComponent (C:\Users\Administrator\Desktop\Vacbid\holioff\node_modules\react-dom\cjs\react-dom-server.node.development.js:5852:7)
    at renderElement (C:\Users\Administrator\Desktop\Vacbid\holioff\node_modules\react-dom\cjs\react-dom-server.node.development.js:6023:7)
    at renderNodeDestructiveImpl (C:\Users\Administrator\Desktop\Vacbid\holioff\node_modules\react-dom\cjs\react-dom-server.node.development.js:6181:11)
    at renderNodeDestructive (C:\Users\Administrator\Desktop\Vacbid\holioff\node_modules\react-dom\cjs\react-dom-server.node.development.js:6153:14)
    at renderNode (C:\Users\Administrator\Desktop\Vacbid\holioff\node_modules\react-dom\cjs\react-dom-server.node.development.js:6336:12)
    at renderChildrenArray (C:\Users\Administrator\Desktop\Vacbid\holioff\node_modules\react-dom\cjs\react-dom-server.node.development.js:6288:7)
    at renderNodeDestructiveImpl (C:\Users\Administrator\Desktop\Vacbid\holioff\node_modules\react-dom\cjs\react-dom-server.node.development.js:6218:7)
    at renderNodeDestructive (C:\Users\Administrator\Desktop\Vacbid\holioff\node_modules\react-dom\cjs\react-dom-server.node.development.js:6153:14)
    at renderNode (C:\Users\Administrator\Desktop\Vacbid\holioff\node_modules\react-dom\cjs\react-dom-server.node.development.js:6336:12)
    at renderHostElement (C:\Users\Administrator\Desktop\Vacbid\holioff\node_modules\react-dom\cjs\react-dom-server.node.development.js:5708:3)
    at renderElement (C:\Users\Administrator\Desktop\Vacbid\holioff\node_modules\react-dom\cjs\react-dom-server.node.development.js:6029:5)

**Comment by ljharb** [comment] 2024-05-31 00:05
Duplicate of #137. You probably need to initialize.

**Closed as not planned by ljharb** 2024-05-31 00:05 UTC
